#!/bin/bash

SOCKET_PATH="/tmp/sx_tmux_socket"
SESSION=$1

if [ -z "$SESSION" ]; then
  SESSION=shared
fi

if tmux -S $SOCKET_PATH has-session -t $SESSION; then
  tmux -S $SOCKET_PATH attach-session -t $SESSION
else
  tmux -S $SOCKET_PATH new-session -s $SESSION
fi
